Models/Comment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace finalyearproject.Models
{
    public class Comment
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int comment_id {  get; set; }
        [Required(ErrorMessage ="comment content can't be empty")]
        public string comment_content {  get; set; }
        public int rating {  get; set; }
        public int user_id {  get; set; }
        [ForeignKey("user_id")]
        public User user { get; set; }
        public int post_id {  get; set; }
        [ForeignKey("post_id")]
        public Post post { get; set; }
        public DateTime date_comment { get; set; }
    }
}

Models/Post.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace finalyearproject.Models
{
    public class Post
    {
        [Key]
        [Required(ErrorMessage ="Post_id can't be empty")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int post_id {  get; set; }
        public int user_id { get; set; }
        [ForeignKey("user_id")]
        public User user { get; set; }
        public string post_title { get; set;}
        [Required(ErrorMessage = "post body can't be empty")]
        public string job_description {  get; set;}
        public string address {  get; set; }
        public string experience {  get; set; }
        public int salary {  get; set; }
        public string Position { get; set;}
        public DateTime date_post { get; set;}
        public string status { get; set;}
        public DateTime expired_date {  get; set;}
        public int limit_candidates {  get; set;}
        public int total_of_candidates {  get; set;}
        public string skill_required {  get; set;}
        public string other_condition {  get; set;}
    }
}

Controllers/CandidateController.cs
using finalyearproject.Models;
using finalyearproject.Models.ViewModel;
using finalyearproject.Repositories;
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;
using System.Runtime.Intrinsics.Arm;

namespace finalyearproject.Controllers
{
    public class CandidateController : Controller
    {
        private AppliedJobRepo appliedjobRepo;
        private PostRepo postRepo;
        private CommentRepo commentRepo;
       private ISession session;
        private readonly ApplicationDBcontext _dbContext;
        private int user_id;
        private string role;
        public CandidateController(ApplicationDBcontext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            _dbContext = dbContext;
            postRepo = new PostRepo(_dbContext);
            appliedjobRepo=new AppliedJobRepo(_dbContext);
            commentRepo=new CommentRepo(_dbContext);
            session = httpContextAccessor.HttpContext.Session;
            user_id = (int)session.GetInt32("user_id");
            role = session.GetString("role");

        }
        public async Task<IActionResult> Index(int post_id)
        {
            List<Appliedjob> jobs = await appliedjobRepo.SearchAllCandidateOfPost(post_id);
            TempData["role"] = role;
            TempData["avatar"] = session.GetString("avatar");
            TempData["name"] = session.GetString("name");
            return View(jobs);
        }

        public async Task<IActionResult> Appliedjobmanagement()
        {
            TempData["user_id"] = user_id;
            TempData["name"] = session.GetString("name");
            TempData["avatar"] = session.GetString("avatar");
            List<Appliedjob> appliedjobs = await appliedjobRepo.SearchAllAppliedByUserId(user_id);
            return View(appliedjobs);
        }

        [HttpPost]
        public async Task AcceptApplied(int appliedjob_id)
        {
            if (CheckInfor())
            {
                await HandleApplied(appliedjob_id);
            }
            
        }
        [HttpPost]
        public async Task RefuseApplied(int appliedjob_id)
        {
            if (CheckInfor())
            {
              await HandleRefuse(appliedjob_id);
            }

        }

        public async Task<IActionResult> Detail(int post_id)
        {
            
            List<Comment> comments = await commentRepo.GetAllCommentByPostId(post_id);
            if (CheckInfor())
            {
                Post post = await postRepo.SearchPostById(post_id);
                Post_CommentViewModel post_comment = new Post_CommentViewModel(post, comments);
                TempData["role"] = role;
                TempData["user_id"] = user_id;
                TempData["name"] = session.GetString("name");
                TempData["avatar"] = session.GetString("avatar");
                if (post.total_of_candidates >= post.limit_candidates)
                {
                    TempData["limited"] = "limited";
                }
                return View(post_comment);
            }
            else return NotFound();
        }
        private async Task HandleRefuse(int id)
        {
            Appliedjob appliedjob = await appliedjobRepo.SearchAppliedById(id);
            if(appliedjob.status!="Refuse")
                appliedjob.post.total_of_candidates--;
            appliedjob.status = "Refuse";
           
            _dbContext.Update(appliedjob);
            await _dbContext.SaveChangesAsync();
        }
        private async Task  HandleApplied(int id)
        {
            Appliedjob appliedjob = await appliedjobRepo.SearchAppliedById(id);
            if (appliedjob.status == "Refuse") appliedjob.post.total_of_candidates++; 
            appliedjob.status = "Accept";
            _dbContext.Update(appliedjob);
           await _dbContext.SaveChangesAsync();
           
        }
        private bool CheckInfor()
        {
            if (user_id != null)
            {
                return true;
            }
            return false;
        }
    }
}

Controllers/PostController.cs
using finalyearproject.Models;
using finalyearproject.Models.ViewModel;
using finalyearproject.Repositories;
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;

namespace finalyearproject.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDBcontext _dbContext;
        private readonly UserRepo userRepo;
        private PostRepo postRepo;
        private CommentRepo commentRepo;
        private ISession Session;
        private int user_id;
        private string role;
        public PostController(ApplicationDBcontext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            _dbContext = dbContext;
            userRepo = new UserRepo(dbContext);
            postRepo = new PostRepo(dbContext);
            commentRepo = new CommentRepo(dbContext);
            Session = httpContextAccessor.HttpContext.Session;
            user_id = (int) Session.GetInt32("user_id");
            role = Session.GetString("role");
            
        }
        public async Task<IActionResult> Index()
        {
            List<Post> posts = await postRepo.SearchAllPostForHome();
            return View(posts);
        }
        public async Task<IActionResult> PostManagement()
        {
            TempData["user_id"] = user_id;
            TempData["avatar"] = Session.GetString("avatar");
            TempData["name"] = Session.GetString("name");
            List<Post> posts= await postRepo.SearchAllPostByUserId(user_id);
            return View(posts);
        }
        
        public async Task<IActionResult> Detail(int post_id)
        {
            User user = await userRepo.SearchUserById(user_id);
            List<Comment> comments = await commentRepo.GetAllCommentByPostId(post_id);
            if (CheckUserInfo())
            {
                Post post = await postRepo.SearchPostById(post_id);
                Post_CommentViewModel post_comment= new Post_CommentViewModel(post,comments);
                TempData["role"] = role;
                TempData["avatar"] = user.avatar;
                TempData["name"] = Session.GetString("name");
                if (post.total_of_candidates>=post.limit_candidates)
                {
                    TempData["limited"] = "limited";
                }
                return View(post_comment);
            }
            else return NotFound();
        }
        public async Task<IActionResult>DetailAdmin(int post_id)
        {
            List<Comment> comments = await commentRepo.GetAllCommentByPostId(post_id);
            if (CheckUserInfo())
            {
                Post post = await postRepo.SearchPostById(post_id);
                Post_CommentViewModel post_comment = new Post_CommentViewModel(post, comments);
                TempData["role"] = role;
                return View(post_comment);
            }
            else return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> AddComment(int post_id, string content,int rating)
        {
            if (CheckUserInfo())
            {
                HandleAddComment(content,post_id,rating); return Ok();
            }
            return BadRequest();
        }

        private void HandleAddComment(string content, int post_id, int rating)
        {
            Comment comment = new Comment();
            comment.user_id = user_id;
            comment.comment_content = content;
            comment.date_comment = DateTime.Now;
            comment.post_id = post_id;
            comment.rating = rating;
            _dbContext.Add(comment);
            _dbContext.SaveChanges();

        }

        public IActionResult CreatePost()
        {
            TempData["user_id"] = user_id;
            TempData["role"] = role;
            TempData["avatar"] = Session.GetString("avatar");
            TempData["name"] = Session.GetString("name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatePost([FromForm] Post post)
        {
            if (CheckUserInfo())
            {
                User user = await userRepo.SearchUserById(user_id);
               string error= HandleCheckPost(post);
                if (error == "")
                {
                    HandleCreatePost(post, user);
                    return RedirectToAction("PostManagement");
                }
                else
                {
                    ViewBag.error=error;
                    return View();
                }
                
            }
            else
            {
                TempData.Clear();
                TempData["new-post"] = post;
                return View();
            }
        }

        private string HandleCheckPost(Post post)
        {
            if (post.expired_date < DateTime.Now)
            {
                return "the expried date must be geater than current date";
            }
            else if (post.salary < 0)
            {
                return "the salary must higher than zero";
            }
            return "";
        }

        public async Task<IActionResult> UpdatePost(int post_id)
        {
            Post post=await postRepo.SearchPostById(post_id);
           
            if (post != null && user_id != null)
            {
                TempData["user_id"] = user_id;
                TempData["role"] = role;
                TempData["avatar"] = Session.GetString("avatar");
                TempData["name"] = Session.GetString("name");
                return View(post);
            }
            else { return NotFound(); }
        }
        [HttpPost]
        public async Task<IActionResult> UpdatePost([FromForm] Post form_post, int post_id)
        {
            Post post = await postRepo.SearchPostById(post_id);
            HandleUpdatePost(HandlePost(post,form_post));
            return RedirectToAction("PostManagement", "Post");
        }

        private Post HandlePost(Post post, Post form_post)
        {
            post.Position = form_post.Position;
            post.salary = form_post.salary;
            post.experience = form_post.experience;
            post.limit_candidates = form_post.limit_candidates;
            post.expired_date = form_post.expired_date;
            post.job_description = form_post.job_description;
            post.skill_required= form_post.skill_required;
            post.other_condition = form_post.other_condition;
            return post;
        }
       

        private void HandleUpdatePost(Post post)
        {
            _dbContext.Update(post);
            _dbContext.SaveChanges();
        }

        private bool CheckUserInfo()
        {
            if (user_id != null && role != null)
            {
                return true;
            }
            else
            {
                return false;
            }

        }

        private void HandleCreatePost(Post post,User user)
        {
            post.date_post = DateTime.Now;
            post.user_id = user_id;
            post.address = user.company.Address;
            post.status = "1";
            post.post_title = "a";
            _dbContext.Add(post);
            _dbContext.SaveChanges();
        }
       
        [HttpPost]
        public async Task DeletePost(int post_id)
        {
            Post post= await postRepo.SearchPostById(post_id);
            post.status = "deleted";
             _dbContext.Update(post);
            await _dbContext.SaveChangesAsync();
        }
        [HttpPost]
        public async Task<IActionResult> AppliedJob(int post_id)
        {
            Post post_targeted = await postRepo.SearchPostById(post_id);
            if (post_targeted.limit_candidates <= post_targeted.total_of_candidates)
            {
                return Ok("out of candidates");
            }
            else
            {
                HandleAppliedJob(post_targeted);
                return Ok("success");
            }
        }
        private async void HandleAppliedJob(Post post_targeted)
        {
            Appliedjob appliedjob = new Appliedjob();
            appliedjob.post_id = post_targeted.post_id;
            post_targeted.total_of_candidates++;
            appliedjob.user_id= user_id;
            appliedjob.status = "in Processing...";
            _dbContext.Add(appliedjob);
            _dbContext.Update(post_targeted);
            _dbContext.SaveChanges();
        }
    }
}

Views/Post/Components/Comment.cshtml
@model finalyearproject.Models.Comment;
<div class="row">
    <div class="col-md-2 col-sm-12">
        <p>@Model.user.Email</p>
        <img src="~/img/Avatar/@Model.user.avatar" style="width: 5rem; height: 5rem" alt="">
    </div>
    <div class="col-md-10 col-sm-12">
        <div class="d-flex flex-column">
            <div class="d-flex justify-content-sm-between">
                @Html.Partial("~/Views/Post/Components/ratingComment.cshtml",Model)
                <p>@Model.date_comment.ToString("yyyy-MM-dd")</p>
            </div>
            <p>@Model.comment_content</p>
        </div>
    </div>
</div>

Views/Post/Components/CreateReport.cshtml
<!-- Logout Modal-->
<div class="modal fade" id="Report" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
               <label>
                   Report Reason
               </label> <textarea id="Reason" aria-label="Report Reason"></textarea>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" id="CreateReport" type="button">
                    <i class="bi bi-exclamation-circle" style="margin-right: 10px"></i>
                    Create
                </button>
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

Views/Post/Components/DeleteModal.cshtml
<!-- Logout Modal-->
<div class="modal fade" id="confirm_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">Delete this selection?</div>
            <div class="modal-footer">
                <button class="btn btn-danger" id="deletebuttonmodal" type="button">
                    <i class="fas fa-trash" style="margin-right: 10px"></i>
                    Delete
                </button>
                <button class="btn btn-secondary"  type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

Views/Post/Components/ItemPost.cshtml
@model finalyearproject.Models.Post

<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Company:  @Model.user.company.company_name</h6>
        <div class="dropdown no-arrow">
            <div class="d-flex gap-4">
                <a asp-controller="Candidate" asp-action="Index" asp-route-post_id="@Model.post_id" class="btn btn-primary">
                    <i class="fas fa-user-circle"></i>
                </a>
                <a asp-controller="Post" asp-action="Detail" asp-route-post_id="@Model.post_id" class="btn btn-info">
                    <i class="fas fa-info-circle"></i>
                </a>
                    <a asp-controller="Post" asp-action="UpdatePost" asp-route-post_id="@Model.post_id" style="text-decoration:none" class="btn btn-warning">
                    <i class="fas fa-edit"></i>
                    </a>
                <button class="btn btn-danger" id="deletebutton_id" data-toggle="modal" data-post-id="@Model.post_id" data-target="#confirm_delete">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-2 col-sm-12">
                <img src="~/img/Avatar/@Model.user.avatar" style="width: 5rem; height: 5rem" alt="">
            </div>
            <div class="col-md-10 col-sm-12">
                <div><label>Postion: </label> <p style="margin-left: 2%;display: inline;">@Model.Position</p></div>
                <div>
                    <label>Job description: </label><p style="margin-left: 2%;display: inline; overflow:hidden">@Model.job_description</p>
                </div>
                <div><label>Address: </label><p style="margin-left: 2%;display: inline; ">@Model.address</p></div>
            </div>
        </div>
    </div>
</div>

Views/Post/Components/PostHome.cshtml
@model finalyearproject.Models.Post;
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Company: @Model.user.company.company_name</h6>
        <div class="dropdown no-arrow">
            <div class="d-flex gap-4">
                <a asp-controller="Candidate" asp-action="Detail" asp-route-post_id="@Model.post_id" class="btn btn-info">
                    <i class="fas fa-info-circle"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-2 col-sm-12">
                <img src="~/img/Avatar/@Model.user.avatar" style="width: 5rem; height: 5rem" alt="">
            </div>
            <div class="col-md-10 col-sm-12">
                <p>Position: @Model.Position</p>
                <p>job description: @Model.job_description</p>
                <p>Address: @Model.address</p>
            </div>
        </div>
    </div>
</div>

Views/Post/Components/Post_search.cshtml
@model IEnumerable<finalyearproject.Models.Post>

@foreach (var item in Model)
{
    @Html.Partial("~/Views/Post/Components/PostHome.cshtml", item)
}

Views/Post/Components/Post_search_management.cshtml
@model IEnumerable<finalyearproject.Models.Post>

@foreach (var item in Model)
{
    @Html.Partial("~/Views/Post/Components/ItemPost.cshtml", item)
}

Views/Post/Components/rating.cshtml
<span class="star-rating">
	<label for="rate-1" style="--i:1"><i class="fas fa-star"></i></label>
	<input type="radio" name="rating" id="rate-1" value=1>
	<label for="rate-2" style="--i:2"><i class="fas fa-star"></i></label>
	<input type="radio" name="rating" id="rate-2" value=2>
	<label for="rate-3" style="--i:3"><i class="fas fa-star"></i></label>
	<input type="radio" name="rating" id="rate-3" value=3>
	<label for="rate-4" style="--i:4"><i class="fas fa-star"></i></label>
	<input type="radio" name="rating" id="rate-4" value=4>
	<label for="rate-5" style="--i:5"><i class="fas fa-star"></i></label>
	<input type="radio" name="rating" id="rate-5" value=5>
</span>

Views/Post/Components/ratingComment.cshtml
@model finalyearproject.Models.Comment;
@{
    var uniqueId = Guid.NewGuid().ToString();
}
<span class="star-rating">
    <label for="rate-1" style="--i:1"><i class="fas fa-star"></i></label>
    <input type="radio" name=@($"{Model.user.Email}-rating_comment-{uniqueId}") id="rate-1" value="1" @(Model.rating == 1 ? "checked" : "") readonly>
    <label for="rate-2" style="--i:2"><i class="fas fa-star"></i></label>
    <input type="radio" name=@($"{Model.user.Email}-rating_comment-{uniqueId}") id="rate-2" value="2" @(Model.rating == 2 ? "checked" : "") readonly>
    <label for="rate-3" style="--i:3"><i class="fas fa-star"></i></label>
    <input type="radio" name=@($"{Model.user.Email}-rating_comment-{uniqueId}") id="rate-3" value="3" @(Model.rating == 3 ? "checked" : "") readonly>
    <label for="rate-4" style="--i:4"><i class="fas fa-star"></i></label>
    <input type="radio" name=@($"{Model.user.Email}-rating_comment-{uniqueId}") id="rate-4" value="4" @(Model.rating == 4 ? "checked" : "") readonly>
    <label for="rate-5" style="--i:5"><i class="fas fa-star"></i></label>
    <input type="radio" name=@($"{Model.user.Email}-rating_comment-{uniqueId}") id="rate-5" value="5" @(Model.rating == 5 ? "checked" : "") readonly>
</span>